name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    -
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag camilodev/routems:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to DockerHub
      run: docker push camilodev/routems:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: CamiloClaure/RouteMs
        token: ${{ secrets.GITHUB_TOKEN }}
