name: Docker Image CI

on:
  push:
    branches: [ "master" ]
env:
  IMAGE_TAG: ${{ github.run_number }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test --coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build_docker:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag camilodev/routems:${{ secrets.MAJOR }}.${{ env.IMAGE_TAG }}
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to DockerHub
      run: docker push camilodev/routems:${{ secrets.MAJOR }}.${{ env.IMAGE_TAG }}
  staging:
    needs: build_docker
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            docker rm -f routems
            docker run -d -p 3000:3000 --name routems camilodev/routems:${{ secrets.MAJOR }}.${{ env.IMAGE_TAG }}
          host: ${{ secrets.SSH_HOST }}
          user: root
          key: ${{ secrets.SSH_KEY}}
